<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pilih Semua_GalleryStyles__image-grid___pOed4</name>
   <tag></tag>
   <elementGuidId>7dbe410c-6693-4ea4-9864-3b3673820cff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.GalleryStyles__image-grid___pOed4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='delete-image']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GalleryStyles__image-grid___pOed4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.idntimes.com/content-images/community/2020/07/saya-ga-main2-9c8300b0c80ba0164cd2c833e3a314ef_200x200.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Liat Muka Saya!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Liat Muka Saya!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-image&quot;)/div[@class=&quot;col-md-4 col-xs-6 GalleryStyles__col-wrap___Y0WuO&quot;]/div[@class=&quot;GalleryStyles__wrapper-image___35fE0&quot;]/img[@class=&quot;GalleryStyles__image-grid___pOed4&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='delete-image']/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Liat Muka Saya!']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
