<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Automotive   Berita Otomotif Terbaru Hari_da8068</name>
   <tag></tag>
   <elementGuidId>448f7097-d32f-4b66-a7eb-9abdcee359ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='idn-editor']/div/div/div[2]/div[3]/div/div/ul/li/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Automotive   Berita Otomotif Terbaru Hari Ini Generasi Millennial  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idn-editor&quot;)/div[@class=&quot;app__container___2_rqd&quot;]/div[1]/div[@class=&quot;app__editor-box___u2Pva&quot;]/div[@class=&quot;draft-fetched&quot;]/div[@class=&quot;app__tabs___wIuDr&quot;]/div[@class=&quot;app__tab-content___3H2CJ&quot;]/ul[1]/li[1]/p[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idn-editor']/div/div/div[2]/div[3]/div/div/ul/li/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Topics'])[1]/following::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/p</value>
   </webElementXpaths>
</WebElementEntity>
