<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Semua_GalleryStyles__check___16cXI</name>
   <tag></tag>
   <elementGuidId>ac627976-0f19-4fe4-a6df-2b8a02b90a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4.col-xs-6.GalleryStyles__col-wrap___Y0WuO > label.GalleryStyles__container-check___1fOI- > span.GalleryStyles__check___16cXI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='delete-image']/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GalleryStyles__check___16cXI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-image&quot;)/div[@class=&quot;col-md-4 col-xs-6 GalleryStyles__col-wrap___Y0WuO&quot;]/label[@class=&quot;GalleryStyles__container-check___1fOI-&quot;]/span[@class=&quot;GalleryStyles__check___16cXI&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='delete-image']/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/label/span</value>
   </webElementXpaths>
</WebElementEntity>
